"""Add fuel truck, customer, aircraft, fuel order tables

Revision ID: 1a764e4d3fa2
Revises: 1ba38c67c062
Create Date: 2025-04-23 02:31:11.923838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a764e4d3fa2'
down_revision = '1ba38c67c062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuel_trucks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('aircraft',
    sa.Column('tail_number', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('tail_number')
    )
    op.create_table('fuel_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DISPATCHED', 'ACKNOWLEDGED', 'EN_ROUTE', 'FUELING', 'COMPLETED', 'REVIEWED', 'CANCELLED', name='fuelorderstatus'), nullable=False),
    sa.Column('tail_number', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('fuel_type', sa.String(length=50), nullable=False),
    sa.Column('additive_requested', sa.Boolean(), nullable=True),
    sa.Column('requested_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('assigned_lst_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_truck_id', sa.Integer(), nullable=True),
    sa.Column('location_on_ramp', sa.String(length=100), nullable=True),
    sa.Column('csr_notes', sa.Text(), nullable=True),
    sa.Column('lst_notes', sa.Text(), nullable=True),
    sa.Column('start_meter_reading', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('end_meter_reading', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('calculated_gallons_dispensed', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('dispatch_timestamp', sa.DateTime(), nullable=True),
    sa.Column('acknowledge_timestamp', sa.DateTime(), nullable=True),
    sa.Column('en_route_timestamp', sa.DateTime(), nullable=True),
    sa.Column('fueling_start_timestamp', sa.DateTime(), nullable=True),
    sa.Column('completion_timestamp', sa.DateTime(), nullable=True),
    sa.Column('reviewed_timestamp', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_csr_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_lst_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_truck_id'], ['fuel_trucks.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_csr_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tail_number'], ['aircraft.tail_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fuel_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuel_orders_assigned_lst_user_id'), ['assigned_lst_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_orders_assigned_truck_id'), ['assigned_truck_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_orders_tail_number'), ['tail_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fuel_orders_tail_number'))
        batch_op.drop_index(batch_op.f('ix_fuel_orders_status'))
        batch_op.drop_index(batch_op.f('ix_fuel_orders_assigned_truck_id'))
        batch_op.drop_index(batch_op.f('ix_fuel_orders_assigned_lst_user_id'))

    op.drop_table('fuel_orders')
    op.drop_table('aircraft')
    op.drop_table('fuel_trucks')
    op.drop_table('customers')
    # ### end Alembic commands ###
