"""Initial migration

Revision ID: 87256ef2abc1
Revises: 05eadf8716a5
Create Date: 2025-04-30 18:28:24.451898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87256ef2abc1'
down_revision = '05eadf8716a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft',
    sa.Column('tail_number', sa.String(length=20), nullable=False),
    sa.Column('aircraft_type', sa.String(length=50), nullable=False),
    sa.Column('fuel_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tail_number')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=True)

    op.create_table('fuel_trucks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('truck_number', sa.String(length=20), nullable=False),
    sa.Column('fuel_type', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_meter_reading', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('truck_number')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_name'), ['name'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('fuel_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DISPATCHED', 'ACKNOWLEDGED', 'EN_ROUTE', 'FUELING', 'COMPLETED', 'REVIEWED', 'CANCELLED', name='fuelorderstatus'), nullable=False),
    sa.Column('tail_number', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('fuel_type', sa.String(length=50), nullable=False),
    sa.Column('additive_requested', sa.Boolean(), nullable=True),
    sa.Column('requested_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('assigned_lst_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_truck_id', sa.Integer(), nullable=True),
    sa.Column('location_on_ramp', sa.String(length=100), nullable=True),
    sa.Column('csr_notes', sa.Text(), nullable=True),
    sa.Column('lst_notes', sa.Text(), nullable=True),
    sa.Column('start_meter_reading', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('end_meter_reading', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('dispatch_timestamp', sa.DateTime(), nullable=True),
    sa.Column('acknowledge_timestamp', sa.DateTime(), nullable=True),
    sa.Column('en_route_timestamp', sa.DateTime(), nullable=True),
    sa.Column('fueling_start_timestamp', sa.DateTime(), nullable=True),
    sa.Column('completion_timestamp', sa.DateTime(), nullable=True),
    sa.Column('reviewed_timestamp', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_csr_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_lst_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_truck_id'], ['fuel_trucks.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_csr_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tail_number'], ['aircraft.tail_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fuel_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuel_orders_assigned_lst_user_id'), ['assigned_lst_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_orders_assigned_truck_id'), ['assigned_truck_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_orders_tail_number'), ['tail_number'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    with op.batch_alter_table('fuel_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fuel_orders_tail_number'))
        batch_op.drop_index(batch_op.f('ix_fuel_orders_status'))
        batch_op.drop_index(batch_op.f('ix_fuel_orders_assigned_truck_id'))
        batch_op.drop_index(batch_op.f('ix_fuel_orders_assigned_lst_user_id'))

    op.drop_table('fuel_orders')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_name'))

    op.drop_table('permissions')
    op.drop_table('fuel_trucks')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_email'))

    op.drop_table('customers')
    op.drop_table('aircraft')
    # ### end Alembic commands ###
