"""add aircraft_type column to aircraft table

Revision ID: ae3b7293103c
Revises: 1a764e4d3fa2
Create Date: 2025-04-23 13:31:37.962120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae3b7293103c'
down_revision = '1a764e4d3fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aircraft_type', sa.String(length=50), nullable=False))
        batch_op.drop_constraint('aircraft_customer_id_fkey', type_='foreignkey')
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=True)

    with op.batch_alter_table('fuel_trucks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('truck_number', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('fuel_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('capacity', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('current_meter_reading', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.drop_constraint('fuel_trucks_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['truck_number'])
        batch_op.drop_column('name')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)
        batch_op.drop_column('hashed_password')
        batch_op.drop_column('name')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_column('password_hash')
        batch_op.drop_column('username')

    with op.batch_alter_table('fuel_trucks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('fuel_trucks_name_key', ['name'])
        batch_op.drop_column('current_meter_reading')
        batch_op.drop_column('capacity')
        batch_op.drop_column('fuel_type')
        batch_op.drop_column('truck_number')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_email'))
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    with op.batch_alter_table('aircraft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('aircraft_customer_id_fkey', 'customers', ['customer_id'], ['id'])
        batch_op.drop_column('aircraft_type')

    # ### end Alembic commands ###
